version: "3.9"

services:
  bot:
    build: .
    environment:
      - VK_GROUP_TOKEN=${VK_GROUP_TOKEN}
      - VK_GROUP_ID=${VK_GROUP_ID}
      - DATABASE_URL=${DATABASE_URL}
      - RESET_DB=${RESET_DB}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vk_bot_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
